name: secure_storage
description: Secure storage package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
    git:
      url: git@github.com:juliansteenbakker/flutter_secure_storage.git
      ref: v10.0.0-beta.4
      path: flutter_secure_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  test: ^1.22.0 #test >=1.24.3 is incompatible with flutter_test from sdk
  very_good_analysis: ^5.0.0+1
