name: cryptocurrency_keys
description: Cryptocurrency keys package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  crypto_keys: ^0.3.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1