name: polygonid
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  flutter:
    sdk: flutter
  hex: ^0.2.0
  polygonid_flutter_sdk:
    git:
      url: ssh://git@github.com/iden3/polygonid-flutter-sdk.git
      ref: e7719385a3471ffa43ce13225f65f35e15211af0
  secp256k1: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
