name: key_generator
description: Private Key Generator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  pinenacl: ^0.3.4
  secp256k1: ^0.3.0
  tezart:
    git:
      url: https://github.com/autonomy-system/tezart.git
dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
