name: oidc4vc
description: OIDC4VC wallet compliance
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  bs58: ^1.0.2
  credential_manifest:
    path: ../credential_manifest
  crypto: ^3.0.3
  dart_bip32_bip44: ^0.2.0
  dart_jsonwebtoken: ^2.13.0
  dart_web3:
    git:
      url: https://github.com/TalaoDAO/dart_web3.git
  did_kit:
    path: ../did_kit
  dio: ^5.3.2
  elliptic: ^0.3.10
  equatable: ^2.0.5
  fast_base58: ^0.2.1
  flutter:
    sdk: flutter
  hex: ^0.2.0
  http_mock_adapter: ^0.6.0
  jose_plus: ^0.4.5
  json_annotation: ^4.9.0
  json_path: ^0.7.2 #latest version creates test issue
  pinenacl: ^0.6.0
  secp256k1: ^0.3.0
  secure_storage:
    path: ../secure_storage
  uuid: ^4.5.1

dependency_overrides:
  ffi: 2.1.0 #didkit from path which depends on ffi ^1.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.0.0+1
